name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ocaml-compiler:
          - "4.14"
          - "5.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3.0.0-alpha
        with:
          opam-repositories: |
            default: https://github.com/hhugo/opam-repository.git#gmp-mingw
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          cache-prefix: "z1"
          allow-prerelease-opam: true

      - name: wintest
        run: |
          bash -c "cat D:/cygwin/etc/setup/setup.rc"
        if: runner.os == 'Windows'

      - run: opam install -v . --with-test --deps-only

      - name: configure tree
        run: opam exec -- sh ./configure

      - name: Build
        run: opam exec -- make

      - name: Run the testsuite
        run: opam exec -- make -C tests test

      - run: opam install . --with-test

      - run: opam exec -- git diff --exit-code
